queue:
    image: rabbitmq
worker:
    build: .
    entrypoint: dp_worker
    links:
        - db:redis
        - queue:rabbitmq
db:
    image: redis
web:
    build: frontend
    links:
        - db:redis
    volumes:
        - frontend:/opt/frontend
    ports:
        - "5000:5000"
